---
abstract: 'Perl API for check_mk livestatus to access runtime'
author:
  - 'Sven Nierlein, <nierlein@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitoring-Livestatus
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Digest::MD5: 0
  IO::Socket::INET: 0
  IO::Socket::UNIX: 0
  Scalar::Util: 0
  Test::More: 0.87
  Thread::Queue: 2.11
  perl: 5.6.0
  threads: 1.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.36
